config/routes.rb
Rails.application.routes.draw do
  root 'movies#index'

  resources :movies do
    resources :reviews
    resources :favorites
  end
  get 'movies/filter/:filter', to: 'movies#index', as: :filtered_movies

  resources :genres

  resources :users
  get "signup", to: "users#new"

  resource :session, only: %i[new create destroy]
  get "sign_in", to: "sessions#new"
  delete "sign_out", to: "sessions#destroy"
end

app/models/genre.rb
class Genre < ApplicationRecord
  before_save :set_slug

  has_many :characterizations, dependent: :destroy
  has_many :movies, through: :characterizations

  validates :name, presence: true, uniqueness: true

  def to_param
    slug
  end

  private

  def set_slug
    self.slug = name.parameterize
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: %i[show edit update destroy]

  def index
    @genres = Genre.order(:name)
  end

  def show
    @movies = @genre.movies
  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)

    if @genre.save
      flash[:notice] = "New genre successfully created!"
      redirect_to @genre
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @genre.update(genre_params)
      flash[:notice] = "Genre successfully updated!"
      redirect_to @genre
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @genre.destroy

    redirect_to genres_url, status: :see_other, alert: "Genre successfully deleted!"
  end

  private

  def set_genre
    @genre = Genre.find_by!(slug: params[:id])
  end

  def genre_params
    params.require(:genre).permit(:name, movie_ids: [])
  end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_form.html.erb
<%= form_with(model: genre) do |f| %>
  <%= render "shared/errors", object: genre %>

  <%= f.label :name %>
  <%= f.text_field :name, autofocus: true %>

  <%= f.label :movies %>
  <div class="checkboxes">
    <%= f.collection_check_boxes(:movie_ids, Movie.all, :id, :title) %>
  </div>

  <%= f.submit %>
<% end %>

app/views/genres/edit.html.erb
<h1>Update Genre</h1>

<%= render "form", genre: @genre %>

app/views/genres/index.html.erb
<h1>Genres</h1>

<ul>
  <% @genres.each do |genre| %>
    <li><%= link_to genre.name, genre %></li>
  <% end %>
</ul>

<% if current_user&.admin? %>
  <section class="admin">
    <%= link_to "New genre", new_genre_path, class: "button" %>
  </section>
<% end %>

app/views/genres/new.html.erb
<h1>Create New Genre</h1>

<%= render "form", genre: @genre %>

app/views/genres/show.html.erb
<% content_for :title, "Genre #{@genre.name} - " %>

<h1><%= @genre.name %></h1>

<% if @movies.present? %>
  <div class="favorite-movies">
    <% @movies.each do |movie| %>
    <div class="movie">
      <%= link_to display_icon(movie), movie %>
      <%= movie.title %>
    </div>
    <% end %>
  </div>
<% else %>
  <p>No movies for this genre.</p>
<% end %>

<% if current_user&.admin? %>
  <section class="admin">
    <%= link_to "Edit", edit_genre_path(@genre), class: "button" %>
    <%= link_to "Delete", @genre, class: "button",
          data: { turbo_method: :delete, turbo_confirm: "Really!?" } %>
  </section>
<% end %>