config/routes.rb
Rails.application.routes.draw do
  root 'movies#index'

  resources :movies do
    resources :reviews
    resources :favorites
  end
  get 'movies/filter/:filter', to: 'movies#index', as: :filtered_movies

  resources :genres

  resources :users
  get "signup", to: "users#new"

  resource :session, only: %i[new create destroy]
  get "sign_in", to: "sessions#new"
  delete "sign_out", to: "sessions#destroy"
end

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <%= content_tag(:div, message, class: "flash #{type}", data: {
    controller: "flash",
    action: "click->flash#close"
  }) %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  Copyright &copy; <%= Time.now.year %> Gustavo Mendel
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav>
    <%= link_to image_tag("logo.png"), root_path %>
    <ul class="left">
      <li>
        <%= nav_link_to "All Movies", movies_path %>
      <li>
      <li>
        <%= nav_link_to "Genres", genres_path %>
      </li>
      <% if current_user&.admin? %>
        <li>
          <%= nav_link_to "New Movie", new_movie_path %>
        </li>
      <% end %>
    </ul>
    <ul class="right">
      <% if current_user %>
        <li>
          <%= nav_link_to current_user.name, current_user %>
        </li>
        <li>
          <%= link_to "Log Out", sign_out_path,
                      data: { turbo_method: :delete },
                      class: "button" %>
        </li>
      <% else %>
        <li>
          <%= link_to "Log In", sign_in_path, class: "button" %>
        </li>
        <li>
          <%= link_to "Sign Up", signup_path, class: "button" %>
        </li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= yield(:title) %>Flix</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag 'placeholder.png' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/header" %>

    <div id="flashes">
      <%= render "layouts/flash" %>
    </div>

    <div class="content">
      <%= yield %>
    </div>

    <%= render "layouts/footer" %>
  </body>
</html>